---
- name: ensure that the postfix config file is in the correct state
  ansible.builtin.template:
    src: main.cf.jinja2
    dest: "{{ postfix_config_file_path }}"
    owner: "{{ postfix_config_file_owner }}"
    group: "{{ postfix_config_file_group }}"
    mode: "{{ postfix_config_file_mode }}"
  vars:
    _config: "{{ postfix_config_file_config }}"
  notify: "{{ postfix_config_file_handlers|default(omit) }}"
  when: postfix_config_file_config != {}
