---
- name: ensure that the system mail aliases database file is in the correct state
  ansible.builtin.template:
    src: aliases.jinja2
    dest: "{{ postfix_aliases_file_path }}"
    owner: "{{ postfix_aliases_file_owner }}"
    group: "{{ postfix_aliases_file_group }}"
    mode: "{{ postfix_aliases_file_mode }}"
  notify:
    - newaliases
