import os

import testinfra.utils.ansible_runner

INVENTORY = os.environ['MOLECULE_INVENTORY_FILE']
HOST_PATTERN = "all"

testinfra_hosts = testinfra.utils.ansible_runner.AnsibleRunner(
    INVENTORY).get_hosts(HOST_PATTERN)


def test_postfix_main_config_file_is_correct(host):
    file_content = """# Ansible managed: Do NOT edit this file manually!

alias_database=hash:/etc/aliases
alias_maps=hash:/etc/aliases
biff=yes
compatibility_level=2
inet_interfaces=all
mailbox_size_limit=0
mydestination=mail.example.org, localhost.example.org, localhost
myhostname=mail.example.org
mynetworks=127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
myorigin=/etc/mailname
readme_directory=no
recipient_delimiter=+
relayhost=
"""
    file = host.file("/etc/postfix/main.cf")
    assert file.exists
    assert file.user == "root"
    assert file.group == "root"
    assert file.mode == 0o440
    assert file.content_string == file_content
