---
- name: ensure that the postfix master config file is in the correct state
  ansible.builtin.template:
    src: master.cf.jinja2
    dest: "{{ postfix_master_file_path }}"
    owner: "{{ postfix_master_file_owner }}"
    group: "{{ postfix_master_file_group }}"
    mode: "{{ postfix_master_file_mode }}"
  vars:
    _config: "{{ postfix_master_file_config }}"
  notify: "{{ postfix_master_file_handlers|default(omit) }}"
  when: postfix_master_file_config != []
