---
- name: ensure apt cache is updated on debian hosts
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: ensure that the postfix package is installed
  ansible.builtin.package:
    name: >-
      {{ postfix_package_name }}{{ '=={}'.format(postfix_package_version)
      if postfix_package_version | length > 0 }}
    state: present
